version: '3.8'
services:
  app:
    pull_policy: "always"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start
