version: '3.8'
services:
  bcel_service:
    image: pokkate/ck-bcel
    # build: .
    pull_policy: always
    env_file:
      - .env
    environment:
      - CK_BACKEND=http://ck-backend:8080
    ports:
      - "3001"
    networks:
      - ck_backend
  
networks:
  ck_backend:
    name: ck_backend
    driver: bridge